apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  bindingRules:
    common: "true"
  mcp: "master"
  sourceFiles:
    - fileName: day2yamls/ClusterLogNS.yaml
      policyName: "subscriptions-policy"
    - fileName: day2yamls/odflvmns.yaml
      policyName: "subscriptions-policy"
    - fileName: day2yamls/odflvmopergroup.yaml
      policyName: "subscriptions-policy"
    - fileName: day2yamls/odflvmsubs.yaml
      policyName: "subscriptions-policy"
