apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "site2odfocpvconf"
  namespace: "ztp-site"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    sites: "site2"
  mcp: "master"
  sourceFiles:
    - fileName: day2yamls/odflvmclustersite2.yaml
      policyName: "config-policy"
    - fileName: day2yamls/ocpvhco411.yaml
      policyName: "config-policy"
