apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "site1odfocpvconf"
  namespace: "ztp-site"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    sites: "site1"
  mcp: "master"
  sourceFiles:
    - fileName: day2yamls/odflvmclustersite1.yaml
      policyName: "config-policy"
    - fileName: day2yamls/ocpvhco410.yaml
      policyName: "config-policy"
    - fileName: day2yamls/opcvspsite1.yaml
      policyName: "config-policy"
