apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ztppvc
  labels:
   app: ztpapplication
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: odf-lvm-vg1 
