allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    ran.openshift.io/ztp-deploy-wave: "20"
  name: odf-lvm-vg1
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.cybozu.com/device-class: vg1
provisioner: topolvm.cybozu.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
