---
apiVersion: v1
kind: Namespace
metadata:
 labels:
    openshift.io/cluster-monitoring: "true"
    kubernetes.io/metadata.name: openshift-storage
 annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
 name: openshift-storage
