kind: Deployment
apiVersion: apps/v1
metadata:
  name: ztphttpd
  labels:
    app: ztphttpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ztphttpd
  template:
    metadata:
      labels:
        app: ztphttpd
    spec:
      containers:
        - name: ztphttpd
          image: quay.io/nitin_etrxengg/ztp/ztphttpd:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
